### ISSUE TITLE
Meeting 30 sept. 2021

### ISSUE THREAD

**Issue by franciscovilchezv** [franciscovilchezv/platform-based-development#3]
Attendees:
@renatoseb 
@franciscovilchezv 

Actions Items:
- [ ] @renatoseb will work in the creation of a POST, PUT and DELETE guide for NodeJS using Express.

**Comment by franciscovilchezv** [comment]
Taken from @renatoseb 

# Todo
- [x] En primer lugar, debemos ejecutar el script `my_chess_club.sql`. O también, podemos seguir el tutorial de `chess_db.md`.
- [x] Seguir el tutorial `api_101.md`, para crear el proyecto de la api. 
- [ ] Realizar la conexión con la base de datos `my_chess_club`

**Comment by franciscovilchezv** [comment]
Not accomplished
